#------python----

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    app: python-app
# specification for (wrapper)pods
spec:
  replicas: 2
  selector:
    matchlabels:
      app: python-app
  #blueprint of pods
  template:
    metadata:
    labels:
      app: python-app
  #specification of container
  spec:
    containers:
      - name: python-container
        image: $DOCKER_CREDS_USR/cloud-python:latest
        ports:
          - containerport: 5000

---
apiVersion: v1
kind: services
metadata:
  name: python-services
spec:
  slector:
    matchlabels:
      app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetport: 5000
  type: ClusterIP
