server {
  listen 80;
  resolver 127.0.0.11 valid=10s;

  # Python service
  location /python {
    set $python_upstream http://python-service:5000;
    proxy_pass $python_upstream/python;
  }
  location /python/health {
    set $python_upstream http://python-service:5000;
    proxy_pass $python_upstream/health;
  }

  # Node service
  location /node {
    set $node_upstream http://node-service:4000;
    proxy_pass $node_upstream/node;
  }
  location /node/health {
    set $node_upstream http://node-service:4000;
    proxy_pass $node_upstream/health;
  }

  # Go service
  location /go {
    set $go_upstream http://go-service:8000;
    proxy_pass $go_upstream/go;
  }
  location /go/health {
    set $go_upstream http://go-service:8000;
    proxy_pass $go_upstream/health;
  }
}
