apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      resolver kube-dns.kube-system.svc.cluster.local valid=10s;

      # Python service
      location /python {
        set $python_upstream http://python-services:5000;
        proxy_pass $python_upstream/python;
      }
      location /python/health {
        set $python_upstream http://python-services:5000;
        proxy_pass $python_upstream/health;
      }

      # Node service
      location /node {
        set $node_upstream http://node-services:4000;
        proxy_pass $node_upstream/node;
      }
      location /node/health {
        set $node_upstream http://node-services:4000;
        proxy_pass $node_upstream/health;
      }

      # Go service
      location /go {
        set $go_upstream http://go-services:8000;
        proxy_pass $go_upstream/go;
      }
      location /go/health {
        set $go_upstream http://go-services:8000;
        proxy_pass $go_upstream/health;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx-app
# nginx pods specification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  # blueprint for nginx pods
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-services
spec:
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
