#stage 1- builder
FROM golang:1.25 as builder
WORKDIR /docker-project
COPY . .
RUN go build -o main .

#stage 2 - Runtime
FROM debian:bookworm-slim           
WORKDIR /docker-project
COPY --from=builder /docker-project/main .
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
COPY . .    
CMD ["./main"]


# healthcheck definition
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD curl -f http://localhost:8000/health || exit 1
